server:
  port: 8080
  address: 0.0.0.0

lavalink:
  server:
    password: youshallnotpass
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    youtubeSearchEnabled: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeMusicMode: false
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
